services:
  app:
    container_name: carosync-app
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      # Mount node_modules as an anonymous volume to prevent host directory from overwriting container's node_modules
      # and to persist dependencies inside the container environment
      - /app/node_modules
      # Mount local .cache folder for Bun's global cache
      - ./cache:/bun-cache
    tty: true
