services:
  app:
    container_name: carosync-app
    image: oven/bun:latest 
    restart: always
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
      - ./cache:/bun-cache
    command: /bin/sh -c "bun install && bun run index.ts"
    tty: true